os: linux
dist: focal
group: edge
arch: arm64-graviton2
virt: lxd

addons:
    apt:
        packages:
            - hwloc
            - libhwloc-dev
            - libfftw3-dev
        sources:
            - ubuntu-toolchain-r-test

language: c
compiler: gcc

script:
  - gcc --version
  - g++ --version
  - cat /proc/cpuinfo
  - uname -a
  - pwd
  - mkdir build
  - cd build
  - pwd
  - cmake -DGMX_USE_RDTSCP=OFF ..
  - make -j 4
  - ./bin/gmx nonbonded-benchmark -all -size 1 -nt 1 -iter 100 -warmup 100
